"""added_kristna_abat

Revision ID: 4415c46de0c6
Revises: f94d11ca5327
Create Date: 2025-02-24 15:31:55.397497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4415c46de0c6'
down_revision: Union[str, None] = 'f94d11ca5327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_index(op.f('ix_document_types_name'), 'document_types', ['name'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=False)
    op.create_index(op.f('ix_item_types_id'), 'item_types', ['id'], unique=False)
    op.create_index(op.f('ix_item_types_name'), 'item_types', ['name'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_schedule_types_id'), 'schedule_types', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_types_name'), 'schedule_types', ['name'], unique=True)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_name'), 'shifts', ['name'], unique=False)
    op.create_index(op.f('ix_transaction_types_id'), 'transaction_types', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_types_name'), 'transaction_types', ['name'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_user_types_id'), 'user_types', ['id'], unique=False)
    op.create_index(op.f('ix_user_types_name'), 'user_types', ['name'], unique=False)
    op.add_column('users', sa.Column('kristna_abat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['kristna_abat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'kristna_abat_id')
    op.drop_index(op.f('ix_user_types_name'), table_name='user_types')
    op.drop_index(op.f('ix_user_types_id'), table_name='user_types')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transaction_types_name'), table_name='transaction_types')
    op.drop_index(op.f('ix_transaction_types_id'), table_name='transaction_types')
    op.drop_index(op.f('ix_shifts_name'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedule_types_name'), table_name='schedule_types')
    op.drop_index(op.f('ix_schedule_types_id'), table_name='schedule_types')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_item_types_name'), table_name='item_types')
    op.drop_index(op.f('ix_item_types_id'), table_name='item_types')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_document_types_name'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
