"""create_religious_documents

Revision ID: 5a7903aa31a6
Revises: c415c46de0c7
Create Date: 2025-03-06 18:41:16.152611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7903aa31a6'
down_revision: Union[str, None] = 'c415c46de0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baptism_documents',
    sa.Column('baptism_date', sa.DateTime(), nullable=True),
    sa.Column('baptism_place', sa.String(), nullable=True),
    sa.Column('amharic_god_parent_name', sa.String(), nullable=True),
    sa.Column('english_god_parent_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('english_christian_name', sa.String(), nullable=True),
    sa.Column('english_father_name', sa.String(), nullable=True),
    sa.Column('english_mother_name', sa.String(), nullable=True),
    sa.Column('amharic_name', sa.String(), nullable=True),
    sa.Column('amharic_christian_name', sa.String(), nullable=True),
    sa.Column('amharic_father_name', sa.String(), nullable=True),
    sa.Column('amharic_mother_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('priest_name', sa.String(), nullable=True),
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('amharic_witness_name_1', sa.String(), nullable=True),
    sa.Column('amharic_witness_name_2', sa.String(), nullable=True),
    sa.Column('english_witness_name_1', sa.String(), nullable=True),
    sa.Column('english_witness_name_2', sa.String(), nullable=True),
    sa.Column('address_witness_1', sa.String(), nullable=True),
    sa.Column('address_witness_2', sa.String(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baptism_documents_amharic_christian_name'), 'baptism_documents', ['amharic_christian_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_amharic_father_name'), 'baptism_documents', ['amharic_father_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_amharic_mother_name'), 'baptism_documents', ['amharic_mother_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_amharic_name'), 'baptism_documents', ['amharic_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_english_christian_name'), 'baptism_documents', ['english_christian_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_english_father_name'), 'baptism_documents', ['english_father_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_english_mother_name'), 'baptism_documents', ['english_mother_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_english_name'), 'baptism_documents', ['english_name'], unique=False)
    op.create_index(op.f('ix_baptism_documents_id'), 'baptism_documents', ['id'], unique=False)
    op.create_table('burial_documents',
    sa.Column('date_of_death', sa.DateTime(), nullable=True),
    sa.Column('place_of_death', sa.String(), nullable=True),
    sa.Column('cause_of_death', sa.String(), nullable=True),
    sa.Column('burial_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('english_christian_name', sa.String(), nullable=True),
    sa.Column('english_father_name', sa.String(), nullable=True),
    sa.Column('english_mother_name', sa.String(), nullable=True),
    sa.Column('amharic_name', sa.String(), nullable=True),
    sa.Column('amharic_christian_name', sa.String(), nullable=True),
    sa.Column('amharic_father_name', sa.String(), nullable=True),
    sa.Column('amharic_mother_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('priest_name', sa.String(), nullable=True),
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('amharic_witness_name_1', sa.String(), nullable=True),
    sa.Column('amharic_witness_name_2', sa.String(), nullable=True),
    sa.Column('english_witness_name_1', sa.String(), nullable=True),
    sa.Column('english_witness_name_2', sa.String(), nullable=True),
    sa.Column('address_witness_1', sa.String(), nullable=True),
    sa.Column('address_witness_2', sa.String(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burial_documents_amharic_christian_name'), 'burial_documents', ['amharic_christian_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_amharic_father_name'), 'burial_documents', ['amharic_father_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_amharic_mother_name'), 'burial_documents', ['amharic_mother_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_amharic_name'), 'burial_documents', ['amharic_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_english_christian_name'), 'burial_documents', ['english_christian_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_english_father_name'), 'burial_documents', ['english_father_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_english_mother_name'), 'burial_documents', ['english_mother_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_english_name'), 'burial_documents', ['english_name'], unique=False)
    op.create_index(op.f('ix_burial_documents_id'), 'burial_documents', ['id'], unique=False)
    op.create_table('marriage_documents',
    sa.Column('english_bride_name', sa.String(), nullable=True),
    sa.Column('english_bride_christian_name', sa.String(), nullable=True),
    sa.Column('english_bride_father_name', sa.String(), nullable=True),
    sa.Column('english_bride_mother_name', sa.String(), nullable=True),
    sa.Column('amharic_bride_name', sa.String(), nullable=True),
    sa.Column('amharic_bride_christian_name', sa.String(), nullable=True),
    sa.Column('amharic_bride_father_name', sa.String(), nullable=True),
    sa.Column('amharic_bride_mother_name', sa.String(), nullable=True),
    sa.Column('date_of_marriage', sa.DateTime(), nullable=True),
    sa.Column('place_of_marriage', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('english_christian_name', sa.String(), nullable=True),
    sa.Column('english_father_name', sa.String(), nullable=True),
    sa.Column('english_mother_name', sa.String(), nullable=True),
    sa.Column('amharic_name', sa.String(), nullable=True),
    sa.Column('amharic_christian_name', sa.String(), nullable=True),
    sa.Column('amharic_father_name', sa.String(), nullable=True),
    sa.Column('amharic_mother_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('priest_name', sa.String(), nullable=True),
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('amharic_witness_name_1', sa.String(), nullable=True),
    sa.Column('amharic_witness_name_2', sa.String(), nullable=True),
    sa.Column('english_witness_name_1', sa.String(), nullable=True),
    sa.Column('english_witness_name_2', sa.String(), nullable=True),
    sa.Column('address_witness_1', sa.String(), nullable=True),
    sa.Column('address_witness_2', sa.String(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marriage_documents_amharic_bride_christian_name'), 'marriage_documents', ['amharic_bride_christian_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_amharic_bride_father_name'), 'marriage_documents', ['amharic_bride_father_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_amharic_bride_mother_name'), 'marriage_documents', ['amharic_bride_mother_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_amharic_bride_name'), 'marriage_documents', ['amharic_bride_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_amharic_christian_name'), 'marriage_documents', ['amharic_christian_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_amharic_father_name'), 'marriage_documents', ['amharic_father_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_amharic_mother_name'), 'marriage_documents', ['amharic_mother_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_amharic_name'), 'marriage_documents', ['amharic_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_bride_christian_name'), 'marriage_documents', ['english_bride_christian_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_bride_father_name'), 'marriage_documents', ['english_bride_father_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_bride_mother_name'), 'marriage_documents', ['english_bride_mother_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_bride_name'), 'marriage_documents', ['english_bride_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_christian_name'), 'marriage_documents', ['english_christian_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_father_name'), 'marriage_documents', ['english_father_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_mother_name'), 'marriage_documents', ['english_mother_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_english_name'), 'marriage_documents', ['english_name'], unique=False)
    op.create_index(op.f('ix_marriage_documents_id'), 'marriage_documents', ['id'], unique=False)
    op.create_table('membership_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('english_christian_name', sa.String(), nullable=True),
    sa.Column('english_father_name', sa.String(), nullable=True),
    sa.Column('english_mother_name', sa.String(), nullable=True),
    sa.Column('amharic_name', sa.String(), nullable=True),
    sa.Column('amharic_christian_name', sa.String(), nullable=True),
    sa.Column('amharic_father_name', sa.String(), nullable=True),
    sa.Column('amharic_mother_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('priest_name', sa.String(), nullable=True),
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('amharic_witness_name_1', sa.String(), nullable=True),
    sa.Column('amharic_witness_name_2', sa.String(), nullable=True),
    sa.Column('english_witness_name_1', sa.String(), nullable=True),
    sa.Column('english_witness_name_2', sa.String(), nullable=True),
    sa.Column('address_witness_1', sa.String(), nullable=True),
    sa.Column('address_witness_2', sa.String(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_documents_amharic_christian_name'), 'membership_documents', ['amharic_christian_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_amharic_father_name'), 'membership_documents', ['amharic_father_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_amharic_mother_name'), 'membership_documents', ['amharic_mother_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_amharic_name'), 'membership_documents', ['amharic_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_english_christian_name'), 'membership_documents', ['english_christian_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_english_father_name'), 'membership_documents', ['english_father_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_english_mother_name'), 'membership_documents', ['english_mother_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_english_name'), 'membership_documents', ['english_name'], unique=False)
    op.create_index(op.f('ix_membership_documents_id'), 'membership_documents', ['id'], unique=False)
    op.drop_index('ix_document_types_name', table_name='document_types')
    op.create_index(op.f('ix_document_types_name'), 'document_types', ['name'], unique=True)
    op.drop_index('ix_item_types_name', table_name='item_types')
    op.create_index(op.f('ix_item_types_name'), 'item_types', ['name'], unique=True)
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_index('ix_transaction_types_name', table_name='transaction_types')
    op.create_index(op.f('ix_transaction_types_name'), 'transaction_types', ['name'], unique=True)
    op.drop_index('ix_user_types_name', table_name='user_types')
    op.create_index(op.f('ix_user_types_name'), 'user_types', ['name'], unique=True)
    op.drop_constraint('phone_number', 'users', type_='unique')
    op.drop_index('ix_users_phone_number', table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    op.create_unique_constraint('phone_number', 'users', ['phone_number'])
    op.drop_index(op.f('ix_user_types_name'), table_name='user_types')
    op.create_index('ix_user_types_name', 'user_types', ['name'], unique=False)
    op.drop_index(op.f('ix_transaction_types_name'), table_name='transaction_types')
    op.create_index('ix_transaction_types_name', 'transaction_types', ['name'], unique=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.drop_index(op.f('ix_item_types_name'), table_name='item_types')
    op.create_index('ix_item_types_name', 'item_types', ['name'], unique=False)
    op.drop_index(op.f('ix_document_types_name'), table_name='document_types')
    op.create_index('ix_document_types_name', 'document_types', ['name'], unique=False)
    op.drop_index(op.f('ix_membership_documents_id'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_english_name'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_english_mother_name'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_english_father_name'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_english_christian_name'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_amharic_name'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_amharic_mother_name'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_amharic_father_name'), table_name='membership_documents')
    op.drop_index(op.f('ix_membership_documents_amharic_christian_name'), table_name='membership_documents')
    op.drop_table('membership_documents')
    op.drop_index(op.f('ix_marriage_documents_id'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_mother_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_father_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_christian_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_bride_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_bride_mother_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_bride_father_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_english_bride_christian_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_mother_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_father_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_christian_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_bride_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_bride_mother_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_bride_father_name'), table_name='marriage_documents')
    op.drop_index(op.f('ix_marriage_documents_amharic_bride_christian_name'), table_name='marriage_documents')
    op.drop_table('marriage_documents')
    op.drop_index(op.f('ix_burial_documents_id'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_english_name'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_english_mother_name'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_english_father_name'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_english_christian_name'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_amharic_name'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_amharic_mother_name'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_amharic_father_name'), table_name='burial_documents')
    op.drop_index(op.f('ix_burial_documents_amharic_christian_name'), table_name='burial_documents')
    op.drop_table('burial_documents')
    op.drop_index(op.f('ix_baptism_documents_id'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_english_name'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_english_mother_name'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_english_father_name'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_english_christian_name'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_amharic_name'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_amharic_mother_name'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_amharic_father_name'), table_name='baptism_documents')
    op.drop_index(op.f('ix_baptism_documents_amharic_christian_name'), table_name='baptism_documents')
    op.drop_table('baptism_documents')
    # ### end Alembic commands ###
